apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-core
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Project which load the argo init config.

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false

--- 

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-load-projects
  namespace: argocd
spec:
  # The project the application belongs to.
  project: argo-core

  # Source of the application manifests
  source:
    repoURL: https://github.com/frvasquezjaquez/argocd-boilerplate.git
    targetRevision: HEAD
    path: argo-core/projects

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  # Sync policy
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
