apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: web-applications
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Project to group all the web applications in the cluster.

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Destination cluster and namespace to deploy the application
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'


  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false